#!/usr/bin/env python3
"""assets/fails-loudly.svg'yi GERCEK ptm ciktisindan uretir.

Her komut gercekten calistirilir; SVG'deki metin, komutun stdout/stderr'ine
yazdigi metnin aynisidir (yalnizca uzun satirlar pencereye sigsin diye
bolunur). Elle yazilmis tek satir yok.

    uv run python arac/terminal-svg.py            # assets/fails-loudly.svg
"""

from __future__ import annotations

import html
import shlex
import subprocess
import sys
import tempfile
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "fails-loudly.svg"
WIDTH_CHARS = 96

UNTRUSTED = """\
name: from-a-stranger
version: "1"
capability: mock-generate
params:
  prompt: "{{ ''.__class__.__mro__[1].__subclasses__() }}"
"""

COMMANDS = [
    ["render", "examples/product-photo.yaml", "--var", "product_name=a red sneaker"],
    ["render", "examples/product-photo.yaml", "--var", "product_nmae=a red sneaker"],
    ["render", "untrusted.yaml"],
]


def run(args: list[str], cwd: Path) -> tuple[str, list[tuple[str, str]]]:
    shown = "$ ptm " + shlex.join(args)
    proc = subprocess.run(
        [sys.executable, "-c", "from prompt_template_manager.cli import main; main()", *args],
        cwd=cwd, capture_output=True, text=True,
    )
    lines: list[tuple[str, str]] = []
    for kind, text in (("out", proc.stdout), ("err", proc.stderr)):
        for raw in text.splitlines():
            for piece in textwrap.wrap(raw, WIDTH_CHARS) or [""]:
                lines.append((kind, piece))
    lines.append(("dim", f"exit {proc.returncode}"))
    return shown, lines


def main() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        (work / "examples").mkdir()
        (work / "examples" / "product-photo.yaml").write_text((ROOT / "examples" / "product-photo.yaml").read_text())
        (work / "untrusted.yaml").write_text(UNTRUSTED)
        blocks = [run(args, work) for args in COMMANDS]

    colors = {"cmd": "#e6edf3", "out": "#5fd977", "err": "#f2777a", "dim": "#5c6b7f"}
    rows: list[tuple[str, str]] = []
    for shown, lines in blocks:
        rows.append(("cmd", shown))
        rows.extend(lines)
        rows.append(("dim", ""))
    rows.pop()

    line_h, top, left = 19, 58, 20
    height = top + line_h * len(rows) + 18
    width = left * 2 + int(WIDTH_CHARS * 7.9)
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" '
        'aria-label="Real ptm output: a render that succeeds, a typo in a variable name caught with a suggestion, '
        'and a template that tries to escape the Jinja sandbox refused with exit 1.">',
        f'<rect width="{width}" height="{height}" rx="10" fill="#161b22"/>',
        f'<rect width="{width}" height="30" rx="10" fill="#1f2630"/><rect y="20" width="{width}" height="10" fill="#1f2630"/>',
        '<circle cx="20" cy="15" r="6" fill="#f2777a"/><circle cx="40" cy="15" r="6" fill="#e3b341"/><circle cx="60" cy="15" r="6" fill="#5fd977"/>',
        f'<text x="{width // 2}" y="20" text-anchor="middle" font-family="ui-monospace, monospace" font-size="12" fill="#8b98a9">'
        "ptm - real output, generated by arac/terminal-svg.py</text>",
        '<g font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace" font-size="13" xml:space="preserve" style="white-space:pre">',
    ]
    for index, (kind, text) in enumerate(rows):
        weight = ' font-weight="700"' if kind == "cmd" else ""
        out.append(
            f'<text x="{left}" y="{top + index * line_h}" fill="{colors[kind]}"{weight}>{html.escape(text)}</text>'
        )
    out += ["</g>", "</svg>", ""]
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(rows)} lines)")


if __name__ == "__main__":
    main()
